@echo off
REM Auto-generated by tools/install.py. Do not edit.
REM Service: freeagent.feishu.bridge --verbose
setlocal
cd /d "%~dp0.."
set "PYTHONIOENCODING=utf-8"
set "PYTHONPATH=src"
if not exist data mkdir data
python -u -m freeagent.feishu.bridge --verbose >> "data\bridge.log" 2>&1
endlocal
