@echo off
REM Auto-generated by tools/install.py. Do not edit.
REM Service: freeagent.delegate --tool-gate --watch 5
setlocal
cd /d "%~dp0.."
set "PYTHONIOENCODING=utf-8"
set "PYTHONPATH=src"
if not exist data mkdir data
python -u -m freeagent.delegate --tool-gate --watch 5 >> "data\executor.log" 2>&1
endlocal
