"""FreeAgent 安装 / 体检器 —— 可选，不是必经步骤。

「可选」是硬约束：核心依赖为空、终端与 Web 只需要标准库，所以
`python -m freeagent.cli.app` 必须始终能直接跑。本脚本是便利。

## 这一版为什么比上一版简单得多

上一版把「进程是否活着」交给 PowerShell 子进程去查，命令行里塞满
``$``、反引号和嵌套引号 —— 而 cmd.exe 用 GBK 码页，Python 里再套一层
subprocess，字符串经过两次编码转换。那是这一版被自己绕进去的地方。

现在**不 spawn 任何 shell**：存活判定只读心跳（``is_stale``），
调度登记交给 Windows 自己的 ``copy``。少一条链路就少一处能坏。

## 三条原则

1. **可选**：不装也能用。
2. **幂等**：已装则跳过并说明，不覆盖已有凭据。
3. **诚实**：最后打印的是**实测**状态，不是「安装成功」。
"""

from __future__ import annotations

import argparse
import getpass
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

#: 要开机自启的东西。(任务名, python -m 后面那段, 额外参数, 日志名)
SERVICES: tuple[tuple[str, str, tuple[str, ...], str], ...] = (
    ("FreeAgent-bridge", "freeagent.feishu.bridge", ("--verbose",), "bridge"),
    ("FreeAgent-executor", "freeagent.delegate",
     ("--tool-gate", "--watch", "5"), "executor"),
)

#: 启动文件夹：按用户生效，**零权限**。
#:
#: 为什么不用计划任务：``schtasks /create`` 即使配 ``/sc onlogon`` 也需要
#: 管理员权限，实测报「拒绝访问」。而自启一个个人事务助手不该要求提权。
#: 触发时机是「登录」而非「开机」—— 你的飞书通道只在你登录后才有用。
STARTUP = Path(os.environ.get("APPDATA", "")) / (
    "Microsoft/Windows/Start Menu/Programs/Startup"
)


def _cmd_wrapper(mod: str, args: tuple[str, ...], log: str) -> str:
    """生成纯ASCII 的 .cmd 内容。

    刻意纯 ASCII（沿用 ``tools/run_feishu.bat`` 的教训）：cmd.exe 会误读
    UTF-8 批处理，非 ASCII 注释会吃掉行边界（``setlocal`` 整行消失）。
    """
    return "\r\n".join([
        "@echo off",
        "REM Auto-generated by tools/install.py. Do not edit.",
        f"REM Service: {mod} {' '.join(args)}",
        "setlocal",
        'cd /d "%~dp0.."',
        'set "PYTHONIOENCODING=utf-8"',
        'set "PYTHONPATH=src"',
        'if not exist data mkdir data',
        f'python -u -m {mod} {" ".join(args)} >> "data\\{log}.log" 2>&1',
        "endlocal",
        "",
    ])


def install_autostart() -> list[str]:
    """把每个服务复制一份到启动文件夹。幂等。"""
    if not STARTUP.is_dir():
        return []
    done: list[str] = []
    tools = REPO / "tools"
    for task, mod, args, log in SERVICES:
        name = f"{task}.cmd"
        local = tools / f"_svc_{name}"
        local.write_text(_cmd_wrapper(mod, args, log),
                         encoding="ascii", newline="")
        target = STARTUP / name
        shutil.copy2(local, target)
        done.append(str(target))
    return done


def remove_autostart() -> list[str]:
    gone: list[str] = []
    for task, _mod, _args, _log in SERVICES:
        name = f"{task}.cmd"
        target = STARTUP / name
        if target.exists():
            target.unlink()
            gone.append(str(target))
    return gone


def check_python() -> bool:
    ok = sys.version_info >= (3, 11)
    print(f"  Python      : {sys.version.split()[0]}"
          f"{'' if ok else '** 需要 3.11+ **'}")
    return ok


def check_feishu_extra() -> None:
    """飞书依赖是可选 extra —— 终端与 Web 不需要它，所以缺失不报错。"""
    try:
        import lark_oapi  # noqa: F401
        print("  lark-oapi   : 已安装")
    except ImportError:
        print("  lark-oapi   : 未安装（只有要用飞书通道才必需）")


def heartbeat() -> dict | None:
    """桥接心跳。

    **只用它判活**，不去查进程、不去查端口 —— 心跳是死进程唯一伪造不了的
    东西，而``is_stale`` 是本项目判活的唯一入口（见 status 模块）。
    刻意不 ``tasklist`` / 不 spawn shell：上一版就是死在那儿。
    """
    from freeagent.feishu.status import is_stale, read_status, status_path

    st = read_status(status_path())
    if st is None:
        return None
    now = time.time()
    up = st.get("updated_at")
    return {
        "state": st.get("state") or "",
        "connected": bool(st.get("connected")),
        "age": (now - float(up)) if isinstance(up, (int, float)) else None,
        "stale": is_stale(st, now=now),
    }


def configure_credentials() -> bool:
    """凭据**已齐就不动**。转调 ``secret_store``，不重写。

    变量名白名单、原子写、BOM 容忍、损坏自愈都是安全相关的既定实现，
    抄一份必然漂移。
    """
    from freeagent.feishu.secret_store import env_path, read_env, write_env

    cur = read_env()
    need = [k for k in ("FEISHU_APP_ID", "FEISHU_APP_SECRET",
                        "FEISHU_ALLOWED_USERS") if not cur.get(k)]
    if not need:
        print("  凭据已齐，不动它。")
        return True

    print(f"\n  缺 {len(need)} 项配置，需要你从飞书开发者后台取：")
    for k in need:
        print(f"    {k}")
    print("  Secret 不回显、不进命令历史。")
    vals = dict(cur)
    for k in need:
        vals[k] = getpass.getpass(f"    {k}: ").strip()
        if not vals[k]:
            print(f"  {k} 留空，放弃配置。")
            return False
    write_env(vals)
    print(f"  已写入 {env_path()}")
    return True


def self_check() -> int:
    """打印实测状态，返回问题数。"""
    print("\n--- 体检（实测，不是复述状态文件）---")
    bad = 0

    hb = heartbeat()
    if hb is None:
        print("  桥接: 没在跑（无心跳）")
        bad += 1
    else:
        verdict = "陈旧（判定为已死）" if hb["stale"] else "新鲜"
        age = "n/a" if hb["age"] is None else f"{hb['age']:.0f}s"
        print(f"  桥接: 心跳 {age} 前，{verdict}，"
              f"state={hb['state']} connected={hb['connected']}")
        if hb["stale"]:
            bad += 1

    for task, _mod, _args, _log in SERVICES:
        name = f"{task}.cmd"
        mark = "已就位" if (STARTUP / name).exists() else "未配置"
        print(f"  自启 {task:<20} {mark}")
    print(f"  启动文件夹: {STARTUP}")

    print("\n  一切正常。" if not bad
          else f"\n  有 {bad} 项需要处理。")
    return bad


def print_next_steps() -> None:
    """装完告诉他接下来干什么。

    抄 ``hermes`` 的 ``setup-hermes.sh``：它在结尾必列 ``hermes setup`` /
    ``hermes gateway`` / ``hermes doctor``。**只说「安装成功」是不够的**——
    用户装完第一个问题是「然后呢」，答不上来就只能去翻文档，而那正是
    「以为这界面没用」的来源之一。

    刻意**按角色分组**：桥接和执行器互相独立，只需要飞书的人不必管执行器。
    """
    print("\n--- 接下来 ---")
    print("  日常直接在飞书里说话即可，桥接会自己连上。")
    print("  想确认它在不在：  python tools\\install.py --check")
    print("  想手动起桥接：    tools\\run_feishu.bat   （先自检凭据，错了当场说清原因）")
    print("  浏览器管事务：    python -m freeagent.web  →  127.0.0.1:8770")
    print("  端到端自测：      python -m pytest")
    print()
    print("  只有要用「委派改代码」才需要执行器（它开机常驻，轮询库等任务）：")
    print("    想先看一眼会派什么：python -m freeagent.delegate --dry-run")
    print("    撤掉开机自启：      python tools\\install.py --uninstall")
    print()
    print("  重启电脑后：桥接与执行器**登录时**自动启动（不是开机时）。")


def main() -> int:
    ap = argparse.ArgumentParser(description="FreeAgent 安装 / 体检")
    ap.add_argument("--check", action="store_true", help="只体检，不改东西")
    ap.add_argument("--uninstall", action="store_true",
                    help="移除启动文件夹里的自启项")
    args = ap.parse_args()

    print(f"FreeAgent 安装器\n仓库：{REPO}\n--- 检查 ---")
    if not check_python():
        return 1
    check_feishu_extra()

    if args.uninstall:
        gone = remove_autostart()
        print("\n--- 已移除 ---")
        for g in gone or ["（本来就没有）"]:
            print(f"  {g}")
        print_next_steps()
        return 0

    if args.check:
        problems = self_check()
        print_next_steps()
        return 1 if problems else 0

    print("\n--- 凭据 ---")
    if not configure_credentials():
        return 1

    print("\n--- 开机自启 ---")
    for path in install_autostart() or []:
        print(f"  已就位 {path}")
    print("  触发时机是「登录」不是「开机」；不需要管理员权限。")

    problems = self_check()
    print_next_steps()
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())